sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t jandevops2024/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jandevops2024/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'eu-north-1'
  app: 'docker'
  env: 'Docker-env'
  bucket_name: 'elasticbeanstalk-eu-north-1-845041271341'
  bucket_path: 'docker'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
